### ISSUE TITLE
Wrong header size received: expected 4, got -1

### ISSUE THREAD

**Issue by michael-schnell** [valdasraps/esj#14]
Running ```mvn verify``` several times produces sometimes an error:
```
Running lt.emasina.esj.EventSendIT
17:22:49,598 ERROR pool-1-thread-3: TcpReceiver:108 - Error in receiver
java.io.IOException: Wrong header size received: expected 4, got -1
	at lt.emasina.esj.tcp.TcpReceiver.run(TcpReceiver.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by valdasraps** [comment]
-1 comes from closed SocketInputStream. It has to be handled gracefully.
